[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
darkpool_perps = "F1b3V2V3dg6YDsfPG6Rc9y769fN4uaZio96st5owXzAr"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --import tsx ./node_modules/mocha/bin/_mocha -t 1000000 \"tests/**/*.ts\""

[hooks]

[test.validator]
startup_wait = 10000
